#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
VERSION=$(grep -o '"version": "[^"]*"' package.json | cut -d'"' -f4)

# Only add version if this is a new commit message (not amend, merge, etc)
if [ -z "$COMMIT_SOURCE" ]; then
    COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
    if [[ ! $COMMIT_MSG =~ ^$VERSION ]]; then
        echo "$VERSION - $(cat $COMMIT_MSG_FILE)" > "$COMMIT_MSG_FILE"
    fi
fi
